# every time you push a new version tag to main ...
on:
  push:
    tags:
      - 'v*'

# determine a new version ...
name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Update version
        id: update-version
        uses: actions/checkout@v4
        run: |
          THIS_VERSION=$(echo "refs/head/v0.0.3" | awk -F'/' '{print $3}')
          echo $THIS_VERSION
          sed -i "s/^version\s*=.*/version = \"$THIS_VERSION\"/" pyproject.toml
          cat pyproject.toml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "updated pyproject.toml version"
          git push
          echo "VERSION=$THIS_VERSION" >> $GITHUB_OUTPUT
      - name: Create release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ steps.update-version.outputs.VERSION }}"